### ISSUE TITLE
Error loading some GBFS links

### ISSUE THREAD

**Issue by jc-ulles** [ds-civic-data/bikeshare-1#10] opened 2023-04-26 15:58 UTC
Hi,
On many French cities (for example Marseille, Lyon...), I get an error when trying to load the `get_station_status()` : 

> "The supplied "city" argument looks like the top-level "gbfs.json" URL, but the webpage for the station_status .json feed doesn't seem to exist. Please supply the actual URL or the name of the city as a string."

I think this is due to the layout of the data in some APIs. Is there a resolution?
Thanks for your help!

**Comment by simonpcouch** [comment] 2023-04-26 16:43
Thanks for the issue! Confirming that I see this as well with one of the Marseille feeds:

``` r
library(gbfs)

get_station_status("https://gbfs.api.ridedott.com/public/v2/marseille/gbfs.json")
#> Error in find_feed_from_top_level(city_, feed_): The supplied "city" argument 
#> looks like the top-level "gbfs.json" URL, but the webpage for the station_status 
#> .json feed doesn't seem to exist. Please supply the actual URL or the name of 
#> the city as a string.
```

<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It looks like, at least for [this feed](https://gbfs.api.ridedott.com/public/v2/marseille/gbfs.json), there is no `station_status` feed:

```
{"data":{"en":{"feeds":[{"name":"gbfs_versions","url":"https://gbfs.api.ridedott.com/public/v2/gbfs_versions.json"},{"name":"free_bike_status","url":"https://gbfs.api.ridedott.com/public/v2/marseille/free_bike_status.json"},{"name":"geofencing_zones","url":"https://gbfs.api.ridedott.com/public/v2/marseille/geofencing_zones.json"},{"name":"system_information","url":"https://gbfs.api.ridedott.com/public/v2/marseille/system_information.json"},{"name":"system_pricing_plans","url":"https://gbfs.api.ridedott.com/public/v2/marseille/system_pricing_plans.json"},{"name":"vehicle_types","url":"https://gbfs.api.ridedott.com/public/v2/marseille/vehicle_types.json"}]}},"last_updated":1682527258,"ttl":0,"version":"2.3"}
```

In that case, there's not much I can do from this package. Do you have any examples of `gbfs.json` feeds that do supply a `station_status` feed but the package is unable to identify it? Could you send the link if so?

**Comment by jc-ulles** [comment] 2023-04-26 16:49
Oh I forgot that there is effectively no data in Marseille. On the other hand, Nancy (and many others) is really problematic: https://transport.data.gouv.fr/gbfs/nancy/gbfs.json

**Comment by jc-ulles** [comment] 2023-04-26 16:51
> Oh I forgot that there is effectively no data in Marseille. On the other hand, Nancy (and many others) is really problematic: https://transport.data.gouv.fr/gbfs/nancy/gbfs.json

Same for Lyon here: https://transport.data.gouv.fr/gbfs/lyon/gbfs.json

**Comment by simonpcouch** [comment] 2023-04-26 16:57
Reproduced, thanks!

This ought to be fixed at some point. In the meantime, supplying the URL of the `station_status` feed itself seems to work fine:

``` r
library(gbfs)

res <- get_station_status("https://transport.data.gouv.fr/gbfs/nancy/gbfs.json")
#> Error in find_feed_from_top_level(city_, feed_): The supplied "city" argument 
#> looks like the top-level "gbfs.json" URL, but the webpage for the station_status 
#> .json feed doesn't seem to exist. Please supply the actual URL or the name of 
#> the city as a string.

res2 <- get_station_status("https://transport.data.gouv.fr/gbfs/nancy/station_status.json")

head(res2)
#>   is_installed is_renting is_returning last_reported num_bikes_available
#> 1            1          1            1    1682527913                   8
#> 2            1          1            1    1682527538                  10
#> 3            1          1            1    1682527674                  18
#> 4            1          1            1    1682527895                   3
#> 5            1          1            1    1682527972                   1
#> 6            1          1            1    1682527763                   7
#>   num_docks_available station_id        last_updated year month day hour minute
#> 1                   7         30 2023-04-26 12:55:11 2023     4  26   12     55
#> 2                  14         29 2023-04-26 12:55:11 2023     4  26   12     55
#> 3                   7          1 2023-04-26 12:55:11 2023     4  26   12     55
#> 4                  12         33 2023-04-26 12:55:11 2023     4  26   12     55
#> 5                  15          6 2023-04-26 12:55:11 2023     4  26   12     55
#> 6                  11         19 2023-04-26 12:55:11 2023     4  26   12     55
```

<sup>Created on 2023-04-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jc-ulles** [comment] 2023-04-26 17:10
Thanks for the alternative, I will use it!

**Comment by simonpcouch** [comment] 2024-01-25 19:06
Thanks for the issue, @jc-ulles. :) The problem has now been resolved and the fix will be in the CRAN version of the package soon.

**Closed as completed** 2024-01-25 19:06 UTC
Labels: bug
